<a href="https://colab.research.google.com/github/rogantan/Analytics/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a = [1, 2, 3, 4, 5]

arr = np.array(a)

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(arr * 2)
print(matrix * 2)


[ 2  4  6  8 10]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [ ]:
zeros = np.zeros((3, 4))
print(zeros)

ones = np.ones((3, 4))
print(ones)

eye = np.eye(5)
print(eye)

linspace = np.linspace(0, 10, 5)
print(linspace)

arange = np.arange(0, 10, 3)
print(arange)

reshaped = arange.reshape((2, 2)) # превращение одномерного массива в двумерный
print(reshaped)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[ 0.   2.5  5.   7.5 10. ]
[0 3 6 9]
[[0 3]
 [6 9]]


In [ ]:
arr1 = np.array([0, 1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8, 9])
hstack = np.hstack((arr1, arr2)) # объединение двух массивов по горизонтали
print(hstack)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
vstack = np.vstack((arr1, arr2)) # объединение по вертикали
print(vstack)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.min(arr), np.max(arr))

3.0
1.4142135623730951
3.0
1 5


Есть данные о зарплатах сотрудников, найти среднюю зарплату, максимальная и минимальная зарплата, стандартное отклонение зарплат, вывод зарплат, которые выше среднего

In [ ]:
arr = np.array([56, 48, 458, 78, 56, 47, 23, 45, 21, 36, 59, 64, 87])

mean_salary = np.mean(arr)
print(f"Среденее значение: {mean_salary}K$")

max_salary = np.max(arr)
print(f"Максимальная зарплата: {max_salary}K$")

min_salary = np.min(arr)
print(f"Минимальная зарплата: {min_salary}K$")

std_salary = np.std(arr)
print(f"Стандартное отклонение зарплаты: {std_salary}")

median_salary = np.median(arr)
print(f"Медиана: {median_salary}")

adove_mean = arr[arr > mean_salary]
print(f"Зарплаты выше среднего: {adove_mean}")

Среденее значение: 82.92307692307692K$
Максимальная зарплата: 458K$
Минимальная зарплата: 21K$
Стандартное отклонение зарплаты: 109.78262545626703
Медиана: 56.0
Зарплаты выше среднего: [458  87]


Анализ данных о продажах в магазине за послдений месяц.


In [ ]:
products_ids = np.array([101, 102, 103, 104, 105])
prices = np.array([10.99, 20.99, 15.24, 55.43, 35.35])
countes = np.array([10, 5, 32, 36, 26])
dates = np.array([
    '2024-01-01', '2024-02-02', '2024-01-05', '2024-02-05', '2024-03-01'
])

total_sales = prices * countes
print(f"Итоговые продажи: {total_sales}")

sum_sales = np.sum(total_sales)
print(f"Итоговая выручка: {sum_sales}$")

average_sales = np.mean(total_sales)
print(f"Средняя выручка: {average_sales:.2f}")

best_produict_id = np.argmax(total_sales)
print(f"Лучший продукт по продажам: {products_ids[best_produict_id]}")

worth_produict_id = np.argmin(total_sales)
print(f"Худший продукт по продажам: {products_ids[worth_produict_id]}")

Итоговые продажи: [ 109.9   104.95  487.68 1995.48  919.1 ]
Итоговая выручка: 3617.11$
Средняя выручка: 723.42
Лучший продукт по прожажам: 104
Худший продукт по прожажам: 102
